#!/usr/bin/env python

import json
import sys

def main():
    tests = []
    for argv in sys.argv[1:]:
        with open(argv) as f:
            parsed = json.load(f)
        tests.extend(parsed['test'])
    tests.sort(key=lambda t: t['autotest']['name'])

    print(json.dumps({'test': tests}, indent=2))

if __name__ == '__main__':
    main()
